# Generated by Django 5.1.7 on 2025-04-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_alter_article_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/"
            ),
        ),
    ]
